org: chengpham
app: lottery-api
service: lottery-api

plugins:
  - serverless-offline

custom:
  tableName: 'lottery-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ca-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["LotteryDynamoDBTable", "Arn" ] }
  environment:
    LOTTERY_TABLE: ${self:custom.tableName}
  apiGateway: 
    shouldStartNameWithService: true

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

resources:
  Resources:
    LotteryDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: lotteryID
            AttributeType: S
        KeySchema:
          -
            AttributeName: lotteryID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}